### ISSUE TITLE
Any plans for typescript support?

### ISSUE THREAD

**Issue by ElliotHan** [klaytn/caver-js#157]
All the web3 packages support typescript within their repos. 
(ex. https://github.com/ethereum/web3.js/tree/2.x/packages/web3-core/types)

Is there any plans for caver-js, regarding types support?

**Comment by kjhman21** [comment]
I'm sorry, but we have no plan for that right now. 
As you might know, since caver-js is an open source project, contribution is always welcome. :)

**Comment by codemaster101** [comment]
Hi any idea when this support would be complete?
We are integrating Klaytn into our system under contract, but it becomes really problematic integrating `JS` packages without Type Definitions.

**Comment by kjhman21** [comment]
@codemaster101 
Please refer to #490. Somebody is working on this. :)

**Comment by codemaster101** [comment]
@kjhman21 hey thanks for the update. The deadline for Klaytn integration is coming (from the Klaytn business side), but it seems the typescript migratoin is still pending. Would there be a timeline for this so that we can schedule our tasks or communicate to the business a better date?

**Comment by kjhman21** [comment]
@codemaster101 
Hmm... I think it is not our top priority, so it would be better not rely on this typescript implementation.

**Comment by codemaster101** [comment]
Sure. Although would probably recommend prioritizing it as and when we receive integration requests we tend to prioritize those chains which can provide type definitions as integration is greatly sped up without the need to go through a chain's SDK that much.

For ex. as this project takes some inspiration from `ethers` it became super easy to integrate ethereum (although no one came forward with a request for it, similarly for `bitcoinjs-lib`). But blockchains like Algorand (which till a few months ago had no type definitions) would usually be pushed back.

Just from a point of view of people who would use your package. In fact if it was just up to me and not up to the business as well, the chances of integration of any blockchain SDK without typedefinitions would have been absolutely null.

**Comment by jimni1222** [comment]
Typescript is supported in latest version. I will close this issue.
