### ISSUE TITLE
npm warn deprecated gulp-util@3.0.8

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#168]
**Is your request related to a problem? Please describe.**
npm warn about following dependencies
- deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Describe the solution you'd like**
remove that warn

**Describe alternatives you've considered**
replace gulp-util to another or remove

**Comment by jimni1222** [comment]
@skqksh 
I will close this because this issue is resolved by #170 :)
