### ISSUE TITLE
Why don't you replace Underscore to Lodash. 

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#172]
**Is your request related to a problem? Please describe.**
- To increase performance of project

**Describe the solution you'd like**
- To replace Underscore to Lodash, so you can use useful methods for array, collections, etc which Underscore not support
- maybe using native js can be good choice, but needs some efforts to follow Lodash
( https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore )

**Describe alternatives you've considered**
- Import lodash than underscore
- migration methods
- check testcases

**Additional context**
- Lodash is normaly bigger than Underscore, but I think It's not problem on this project
- In my test Lodash is faster than Underscore
- Lots of update are in Lodash
- I wonder your opinion

**Comment by kjhman21** [comment]
Could you please share the replacement?
- How much code change required to do that?
- How much faster using Lodash?

**Comment by skqksh** [comment]
@kjhman21 

I tested with recent version of them.
And I found that performance is not really much different between both

* test scource code : https://github.com/skqksh/lodash-vs-underscore
(it cover a few of test cases)

Now I think, using Lodash is not just for increase speed

Nevertheless, Actually I prefer to use Lodash by following reasons. (not meaning lodash is better)
- I like to follow trends
https://trends.google.com/trends/explore?cat=733&date=today%205-y&q=lodash,underscore
- lodash updates steadily ( more stars, commit and contributors )
https://github.com/lodash/lodash/
https://github.com/jashkenas/underscore

Maybe you can get some ideas form following blogs
- https://github.com/indongyoo/functional-javascript/wiki/3.1-Underscore.js-%EC%86%8C%EA%B0%9C
- https://benmccormick.org/2014/11/12/underscore-vs-lodash

Needs to check method list if replace to Lodash in this project
```
// _.range
// _.omit
// _.last
// _.chain
// _.contains
// _.isEmpty
// _.isString
// _.isNumber
// _.isObject
// _.isArray
// _.isFunction
// _.extend
// _.isUndefined
// _.isNull
// _.each
// _.find
// _.isBoolean
// _.map
```

And I just want to listen your opinion

**Comment by kjhman21** [comment]
What I wonder is that how many code lines should be changed to this replacement?
Also, we need to make sure that this change is functionally correct.

Could you discuss about this? First, how many lines should be changed?

**Comment by kjhman21** [comment]
You can also contribute it directly using PR. :)

**Comment by skqksh** [comment]
> What I wonder is that how many code lines should be changed to this replacement?
> Also, we need to make sure that this change is functionally correct.
> 
> Could you discuss about this? First, how many lines should be changed?

153 codes  should be changed.
![image](https://user-images.githubusercontent.com/16040418/70217461-8b651180-1784-11ea-82eb-ad8639cf9309.png)

I'll try with PR ~!

**Comment by skqksh** [comment]
test speed was almost same between lodash and underscore

( millisecond )
![image](https://user-images.githubusercontent.com/16040418/70224100-054ec800-1790-11ea-8da7-d8d26f61ee31.png)
