### ISSUE TITLE
webpack scrypt.js: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by hspark80** [klaytn/caver-js#173]
**Describe the bug**
A warning is issued to build vue-app using 'carver-js v1.2.1'

**How to reproduce**

**Expected behavior**

**Attachments**
**** LOG ****
 WARNING  Compiled with 1 warnings                                                                                                                                               
 warning  in ./node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/scrypt.js

Critical dependency: the request of a dependency is an expression

**Environment (please complete the following information)**
caver-js v1.2.1
node v10.16.3
webpack v4.40.2

 - OS and its version [windows10]

**Additional context**

There was the same problem with web3.js.
The problem that occurred in v1.2.1 appears to have disappeared since v1.2.2
Please check the link.
https://github.com/ethereum/web3.js/issues/3018

**Comment by kjhman21** [comment]
Thanks for the report.
It would appriciate if you make a PR to fix this using https://github.com/ethereum/web3.js/commit/fea7a9b7652193bc87446f474e5389dabf65a9b9. :)

**Comment by jimni1222** [comment]
I closed this issue because this is resolved through #184 .
If you want to discuss about this more, please feel free to re-open :)
