### ISSUE TITLE
What's the rules to add test case

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#174]
When I want to add some test case between '...-ETC-097' and '...-ETC-098'

how should I mark test name

**example**
```
describe('caver.utils.randomHex', () => {
    context('CAVERJS-UNIT-ETC-097: input: valid value', () => {
          // some test codes
        })
    })

    context('CAVERJS-UNIT-ETC-098: input: invalid value', () => {
          // some test codes
    })
})

describe('caver.utils.isBN', () => {
    context('CAVERJS-UNIT-ETC-099: input: BN type', () => {
          // some test codes
    })

```

**Comment by kjhman21** [comment]
Thanks for filing issues. We will add a description about the naming convention of the test cases.
@jimni1222 Could you do this, please?

**Comment by jimni1222** [comment]
@skqksh 

Currently, naming rules for managing test code are being organized.

There is no public naming convention yet, so if you want to add test code, you don't have to assign naming for now.

When writing the test code, please explain which case the code is for and upload it. :)
