### ISSUE TITLE
How can I set config for test

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#180]
To test caver-js, it needs some env-config to use like 'process.env.privateKey' 

Please explain how to set config them

**Comment by kjhman21** [comment]
@jimni1222 Could you explain how to do that?

**Comment by jimni1222** [comment]
@skqksh 
Hi :) Sorry for the late reply;

When testing, you need an account(or accounts) with enough KLAY.

Depending on test code, you only need one account for sending transactions, or two accounts for paying fees.

If you have built a separate network for testing, modify the information in testrpc.js and testWebsocket.js to suit your network.
If not, you need an account with enough KLAY on the Baobab testnet set by default.

If the above preparation is complete, you can run the test with below command.
$ privateKey='0x ...' privateKey2='0x ...' mocha ./test/-.js.

If there is more question about this, please feel free to reopen this issue !

**Comment by skqksh** [comment]
@jimni1222 
I appreciate your kindness
