### ISSUE TITLE
Any plans for provide caver-js as CDN?

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#204]
caver contains method for only browser like `wallet.save`.

so. I wonder if you have any plans for.

thanks

**Comment by jimni1222** [comment]
Hi :)

Currently PR has been posted to cdn.js repo, but I have not received any feedback.
If caver-js can't be uploaded to cdn.js, i'll find another way.

Thank you for reminding me about this, and happy new year :) 

refer https://github.com/cdnjs/cdnjs/pull/13432

**Comment by skqksh** [comment]
Thanks. happy new year!

**Comment by jimni1222** [comment]
I will close this issue :) 
Please see https://cdnjs.com/libraries/caver-js
