### ISSUE TITLE
Error: utils.isBN returns wrong boolean with an fake object

### ISSUE THREAD

**Issue by skqksh** [klaytn/caver-js#205]
**Describe the bug**

caver.utils.isBN returns 'true' but it should have to return 'false'

```[javascript]
 const notBn = {}
notBn.constructor = {}
notBn.constructor.name = 'BN'
console.log(caver.utils.isBN(test))
```

**How to reproduce**
same with above

**Expected behavior**
caver.utils.isBN should work as like as BN.js works

**Attachments**
web3.js already covered that

**Environment (please complete the following information)**
 - caver-js ver 1.3.1

**Additional context**
NA

**Comment by jimni1222** [comment]
Hi :) 

Is this issue related with https://github.com/ethereum/web3.js/issues/1777?
I will apply this modification to caver-js. 
And also i will add test case what you describe above.

Thank you for reporting this issue !

**Comment by jimni1222** [comment]
@skqksh 
Hi, PR is uploaded :) 
https://github.com/klaytn/caver-js/pull/207

If there is any opinion about this change, please feel free to comments on PR.
