### ISSUE TITLE
I found the problem with sendTransaction Hang

### ISSUE THREAD

**Issue by lolgolflol** [klaytn/caver-js#206]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I found the problem when I call the sendTransaction to mainnet and sometimes it makes a process too long and hang but it is not too often. because in my production too many submit to mainnet per second 

**Describe the solution you'd like**
I would like sendTransaction function has an options timeout for the process is terminated by itself.
Because now my terminal or console hang and I must ctrl+c for terminated. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jimni1222** [comment]
@lolgolflol 
Hi :)

Doesn't it work by specifying the timeout option when creating the provider?
You can set the timeout like this: "const caver = new Caver (mainnet_url, {timeout: 1000})"

If it doesn't work, please tell me. Thank you for reporting the issue. :)

**Comment by lolgolflol** [comment]
Hi, @jimni1222 
Okay, Thank you.  
I did not know that we can set the timeout in Provider before, but this code works for me.

```
const caver = new Caver(
  new Caver.providers.HttpProvider(mainnet_url, {
    timeout: 44000
  })
);
```

**Comment by jimni1222** [comment]
@lolgolflol 
I'm happy to solve your problem.
Thanks again! :)
