### ISSUE TITLE
Starting with caver-js isn't as expected 

### ISSUE THREAD

**Issue by hyunyoung86** [klaytn/caver-js#226]
Hello, I'm trying out klaytn with caver-js on Baobab.
I'm using Amazon EC2 instance (free version, Amazon Linux 2 AMI) and followed installation steps in here: https://github.com/klaytn/caver-js/#installation

caver-js was installed with dependencies described in github and completed without any errors.

The followings are console logs in my EC2 session:

[ec2-user@ip-172-31-43-162 ~]$ cd klaytn/
[ec2-user@ip-172-31-43-162 klaytn]$ ls
node_modules  package.json  package-lock.json
[ec2-user@ip-172-31-43-162 klaytn]$ node
> const Caver = require('caver-js')
undefined
> const caver = new Caver('https://api.baobab.klaytn.net:8651/')
undefined
> caver.klay.getNodeInfo().then(console.log)
Promise {
  pending,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
> Klaytn/v1.3.0/linux-amd64/go1.13.3

> const account = caver.klay.accounts.create()
undefined

> account
Account {
  address: [Getter/Setter],
  accountKey: [Getter/Setter],
  privateKey: [Getter/Setter],
  signTransaction: [Function: signTransaction],
  feePayerSignTransaction: [Function: feePayerSignTransaction],
  sign: [Function: sign],
  encrypt: [Function: encrypt],
  getKlaytnWalletKey: [Function: getKlaytnWalletKey] }

I also checked const caver:

> caver
Caver {
  use: [Function: bound ],
  currentProvider: [Getter/Setter],
  _requestManager:
   RequestManager {
     provider:
      HttpProvider {
        host: 'https://api.baobab.klaytn.net:8651/',
        timeout: 0,
        headers: undefined,
        connected: false },
      ....

`connected`  in `HttpProvider` sometimes is shown as `true`, but I still got no bound data on `const account`.

Could you help me with this?

**Comment by jimni1222** [comment]
Hello. :) First of all, thank you for reporting the issue.

The **connected** variable inside the provider is toggled based on the result of the RPC call with the node.
When you first create a Caver instance, you can see that the provider's connected is **false**, but after the successful RPC call with the node, it changes to **true**.

And since property of account is composed of getter and setter,
> account.address
> account.accountKey
> account.privateKey
You can check the value through getter like this :)

If the explanation was not enough, please feel free to ask.

**Comment by hyunyoung86** [comment]
Thank you jimmi1222!  Had it all been solved!
