### ISSUE TITLE
KIP17 is missing at npmjs.com

### ISSUE THREAD

**Issue by miraten** [klaytn/caver-js#246]
I installed caver-js v 1.4.0 from npmjs.com.
In the GitHub source, there exists KIP17 at `packages/caver-klay/caver-klay-kct/contract/token/KIP17`.
However it is missing when I download it from npmjs.com.

**Comment by jimni1222** [comment]
Hi. Thank you for reporting the bug first.

In the process of deploying caver-js v1.4.0, the implementation for KIP17 is missing.
The caver-js v1.4.1-rc.1 version, including the KIP17 package, has been released now.
So you can use caver-js v1.4.1-rc.1(https://www.npmjs.com/package/caver-js/v/1.4.1-rc.1) for KIP17.
Also caver-js v1.4.1 will be released today.

Thank you again :)

**Comment by jimni1222** [comment]
I will close this issue now :) If you want to talk something more about this, feel free to talk to comment here!
