### ISSUE TITLE
npm ERR! Unexpected token w in JSON at position 0 while parsing near 'w{ npm ERR!   "name": "server...'

### ISSUE THREAD

**Issue by heipacker** [klaytn/caver-js#459]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - caver-js version or git revision that exhibits the issue
 - OS and its version [e.g. macOS/10.14]

**Additional context**

**Comment by jimni1222** [comment]
This doesn't seem to be a caver-js issue. Please refer to the link below.

https://stackoverflow.com/questions/54656780/error-npm-err-unexpected-token-in-json-at-position-0-while-parsing-near
