### ISSUE TITLE
Contract Address Receive KLAY?

### ISSUE THREAD

**Issue by boy-good** [klaytn/caver-js#528]
Freely describe your questions or issues here.

i write these function on contract,but cannot receive KLAY?How to do?

fallback() external payable {}
 receive() external payable {}

**Comment by boy-good** [comment]
![telegram-cloud-photo-size-5-6172590465552067886-y](https://user-images.githubusercontent.com/39320533/132176499-1da644db-bdb0-46fc-b4c9-8d7ea4f02d9b.jpg)

**Comment by boy-good** [comment]
can't use address(this).balance to query KLAY balance??

**Comment by jimni1222** [comment]
This is not caver-js issue. Please post your question in [Klaytn Forum](https://forum.klaytn.com/).
