### ISSUE TITLE
Event subscription as the first request results in fromBlock parameter to be deleted

### ISSUE THREAD

**Issue by jyeoniii** [klaytn/caver-js#570]
**Describe the bug**
Race condition arises when the first request made by a Websocket provider is a subscription to an event which includes a request for historical logs.
It's been fixed in `web3.js` but it seems that the same bug still exists in `caver-js`.
* Bug Report Issue: https://github.com/ChainSafe/web3.js/issues/3389
* Bugfix PR: https://github.com/ChainSafe/web3.js/pull/3455

**How to reproduce**
Create `Caver` using `WebsocketProvider` and request event subscription for the first request. 
```
const caver = new Caver('wss://api.baobab.klaytn.net:8652');
const contract = new caver.klay.Contract(abi, contractAddress);
contract.events.allEvents({ fromBlock: 0 }).on('data', console.log);
```
If I call something like `await caver.klay.getAccounts()` before the subscription, it works fine. 

**Expected behavior**
All events of the contract from block 0 should be retrieved.

**Environment (please complete the following information)**
 - caver-js version: 1.6.6
 - OS and its version: macOS 11.3.1

**Comment by jimni1222** [comment]
@jyeoniii Thank you for reporting. You can use caver-js v1.6.7-rc.1 :)
