### ISSUE TITLE
Kaikas pop-up causes page refresh when running on remote server

### ISSUE THREAD

**Issue by elliotwoods** [klaytn/caver-js#578]
When deploying an app that uses Kaikas wallet to an online server, a new behavior appears which is not present when running the web app on localhost.

Specifically, a call to `await caver.klay.signTransaction(transaction);` will cause the page to refresh.

This behavior can be seen at http://toitoitoi.herokuapp.com/redeem.html

If you connect to wallet and then type a key into the box (try any random key) and select Redeem, the code will get here:

![image](https://user-images.githubusercontent.com/328294/151132032-0498960a-25fe-4712-89c5-6b6268f1ee44.png)

At this point the Kaikas pop-up appears, but the page itself refreshes (so the system fails since it's reset). Tested on Chrome and Edge.

The system works fine when running a local node.js server.

 - Kaikas 1.9.1
 - Caver 1.6.1

**Comment by jimni1222** [comment]
Hi, Thank you for posting an issue.
This seems like a Kaikas issue not caver-js.
Can you inquire this issue in [here](https://forum.klaytn.com/)?

**Comment by elliotwoods** [comment]
I fixed the isse. Thanks for quick response
