### ISSUE TITLE
Property 'keyring' does not exist on type 'IWallet'.

### ISSUE THREAD

**Issue by narendracode** [klaytn/caver-js#582]
**Environment **
 - caver-js version 1.6.7
 - macOS/11.1]

```
import Caver from 'caver-js';
const caver = new Caver('...');
const keyring = caver.wallet.keyring.generate()
```
typescript build error : **_"Property 'keyring' does not exist on type 'IWallet'."_**

I find some of the implementation methods are missing in `IWallet` interface as mentioned in doc here(mentioned here in [doc](https://docs.klaytn.com/dapp/sdk/caver-js/api-references/caver.wallet#class)

`https://github.com/klaytn/caver-js/blob/master/index.js`
```
function Caver(..) {
    ...
    this.wallet = new KeyringContainer()
}
```

`https://github.com/klaytn/caver-js/blob/master/types/index.d.ts`
```
export default class Caver {
    ...
    wallet: IWallet
    ...
}
```

Solutions : 
1.Either IWallet should have all those methods 

```
export class IWallet {
    generate(num: number): string[]
    sign(address: string, transaction: Transaction): Promise<Transaction>
    signAsFeePayer(address: string, transaction: FeeDelegatedTransaction): Promise<FeeDelegatedTransaction>
    isExisted(address: string): boolean
    remove(address: string): boolean
    ... // methods to be added here
}
```

or 2.  wallet type requires to be updated as `KeyringContainer`  in `Caver` class.
https://github.com/klaytn/caver-js/blob/master/types/index.d.ts

Looking forward to your update on this issue and I can create PR accordingly.

**Comment by jimni1222** [comment]
Hi, Please use [latest rc version.](https://github.com/klaytn/caver-js/tags)
I fixed type in there.
Please reopen if there is still an issue.
