### ISSUE TITLE
Klaytn testnet is not working properly

### ISSUE THREAD

**Issue by davidlee-crastonic** [klaytn/caver-js#609]
I am using https://api.baobab.klaytn.net:8651 for the api url for creating new Caver object, but it fails to catch account info.

**Comment by kjhman21** [comment]
@Talented-Developer Hi, thanks for filing an issue.
Could you explain little bit more about your code? How do you call that? You can find a reference code in this [page](https://docs.klaytn.com/dapp/sdk/caver-js/getting-started#sending-klay-at-a-glance).
