### ISSUE TITLE
caver-js/types/packages/caver-rtm/src/index.d.ts type mismatch

### ISSUE THREAD

**Issue by Seunghwan96** [klaytn/caver-js#631]
```typescript
klay_getCouncilSize(blockNumber: BlockNumber, callback?: (error: Error, result: number) => void): Promise<number>
```

여기서 blockNumber 는 optional이라서 `blockNumber: BlockNumber` -> `blockNumber?: BlockNumber` 로 수정되어야 하지 않을까요? 혹시나 아니라면 죄송합니다... 
(참고자료 https://docs.klaytn.com/dapp/sdk/caver-js/v1.4.1/api-references/caver.klay/block#getcouncilsize)

**Comment by jimni1222** [comment]
Hi, thank you for reporting this.
i think what you said is correct, and i will modify that.

And klaytn/caver-js is a public repo, so I would appreciate it if you could communicate using English.
Thank you :)

**Comment by jimni1222** [comment]
I fixed in https://github.com/klaytn/caver-js/pull/633

**Comment by Seunghwan96** [comment]
yes. thank you! 👍👍👍
