### ISSUE TITLE
caver-js/types/packages/caver-rtm/src/index.d.ts getBlockNumber type mismatch

### ISSUE THREAD

**Issue by Seunghwan96** [klaytn/caver-js#632]
```
klay_blockNumber(callback?: (error: Error, result: string) => void): Promise<string>
```

여기서 `string` 으로 리턴된다고 하는데 docs에서는 `number` 로 리턴한다고 나와있습니다. 혹시나 아니라면 죄송합니다.

(참고자료
https://docs.klaytn.com/dapp/sdk/caver-js/v1.4.1/api-references/caver.klay/block#getblocknumber)

**Comment by jimni1222** [comment]
I fixed in https://github.com/klaytn/caver-js/pull/633.
Please use english to communicate in this public caver-js repository. ;-;
