### ISSUE TITLE
caver-js/types/packages/caver-utils/src/index.d.ts hexToNumber type mismatch 

### ISSUE THREAD

**Issue by Seunghwan96** [klaytn/caver-js#634]
```
hexToNumber(value: string | number | BN): string
```

I think this should be fixed to 
`hexToNumber(value: string | number | BN): string` -> `hexToNumber(value: string | number | BN): number`.

ref) https://docs.klaytn.com/dapp/sdk/caver-js/api-references/caver.utils#hextonumber

**Comment by jimni1222** [comment]
I fixed https://github.com/klaytn/caver-js/pull/635

**Comment by kjhman21** [comment]
@Seunghwan96 Thanks for sharing the issues. Of course, since klaytn and caver-js is an open-source repository, you can also contribute. :)
