### ISSUE TITLE
support Webpack 5.x  

### ISSUE THREAD

**Issue by HaeSim** [klaytn/caver-js#669]
Have any plans to support webpack version 5.x ?

**Comment by jimni1222** [comment]
Hi, you can see [here](https://github.com/klaytn/caver-js#using-webpack--5) for details about how to setting with webpack 5.

**Comment by HaeSim** [comment]
oh, I missed it. Thank you.
I'm using CRA, so I should use react-app-rewired.
bye😊

**Comment by HaeSim** [comment]
oh, I missed it. Thank you.
I'm using CRA, so I should use react-app-rewired.
bye😊
