### ISSUE TITLE
security vulnerability dependabot alerts

### ISSUE THREAD

**Issue by Byeong-jun-Kim** [klaytn/caver-js#676]
node-forge ^0.10.0 version of ipfs-http-client ^49.0.4 is used in this project, and there are many security vulnerability alerts in this package version. Can you solve it through versioning?

**Comment by jimni1222** [comment]
@Byeong-jun-Kim You can use caver-js v1.0.1-rc.1. Thanks

**Comment by Byeong-jun-Kim** [comment]
Thank you for your quick action! :)

**Comment by Byeong-jun-Kim** [comment]
There is one more deprecated package multihashes(moved on multiformats). If you have time, please check it

**Comment by jimni1222** [comment]
I don't think [multihashes](https://www.npmjs.com/package/multihashes) is deprecated. And also when i check with `npm audit`, i could not find anything related with that.

**Comment by Byeong-jun-Kim** [comment]
I don't know why that package on npm.com doesn't show any deprecated marks. However, if you go to github, [the repository](https://github.com/multiformats/js-multihash) is archived, and if you read the readme of [multiformats](https://github.com/multiformats/js-multiformats), there is information that the multihashes package is inherited.

**Comment by jimni1222** [comment]
@Byeong-jun-Kim I modified to use multiforamts instead of multihashes. https://github.com/klaytn/caver-js/pull/699
Thank you for reporting.

**Comment by Byeong-jun-Kim** [comment]
Wow! Thankyou 👍

**Comment by jimni1222** [comment]
> Wow! Thankyou 👍

caver-js v1.9.1-rc.2 is released, and you can use it.

**Comment by Byeong-jun-Kim** [comment]
Thank you so much

**Comment by nohkwak** [comment]
@Byeong-jun-Kim 
Caver-js is currently using the ipfs-http-client 57.0.3 version module, but there are compatibility issues when using it with React, so downgrading is being considered.

I can't check the information about the vulnerability as shown in the link below.
https://security.snyk.io/package/npm/ipfs-http-client/versions?page=3
May I know what vulnerability was in ipfs-http-client 49.0.4?
