### ISSUE TITLE
AbstractTransaction removed gasPrice caver-js 1.9.0

### ISSUE THREAD

**Issue by jaeholee1118** [klaytn/caver-js#695]
When make transaction, we use gasPrice field in AbstractTransaction class.
but this field removed over caver-js update 1.9.0, replacement AbstractTransaction any class?

**Comment by jimni1222** [comment]
Hello, thank you for posting the issue. I apologize for this.

The `gasPrice` field was moved from AbstractTransaction to each classes (except for EthereumDynamicFee tx) when the EthereumDynamicFee transaction type is introduced.
As a result, the before usage was broken.
For this, a [PR](https://github.com/klaytn/caver-js/pull/696) has been posted, that a gasPrice getter/setter has been added to AbstractTransaction.
If this change is included, i think that the existing usability can be used as is.
If there is any worries, please share to me.

When the PR is merged, it will be distributed as v1.9.1-rc.1.

**Comment by jimni1222** [comment]
@jaeholee1118 You can use caver-js v1.0.1-rc.1. Thanks
