### ISSUE TITLE
Caver instance have currentProvider, but it is not defined as type

### ISSUE THREAD

**Issue by godtaehee** [klaytn/caver-js#709]
**Is your request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Sir, I wrote all of my issue in this [my repository](https://github.com/godtaehee/caver-js-error-report/tree/main)

Please refer it.

**Comment by kjhman21** [comment]
@godtaehee Your PR is now merged. If it is resolved, please also close this issue too. Thanks. 
We will publish a new version with the change soon!

**Comment by godtaehee** [comment]
@kjhman21 Yeah! Thanks!!

**Comment by jimni1222** [comment]
@godtaehee I released v1.9.1-rc.4 version. You can use this version from now. Thank you for contribution again. =)
