### ISSUE TITLE
test for caver.utils.xyPointFromPublicKey often fails in circleci

### ISSUE THREAD

**Issue by thatlook** [klaytn/caver-js#85]
The test for `caver.utils.xyPointFromPublicKey` seems to fail sometimes.
 
<img width="829" alt="Screen Shot 2019-08-27 at 4 48 52 PM" src="https://user-images.githubusercontent.com/33795235/63751607-a9e88080-c8ea-11e9-8b1c-2b948cb2b2de.png">

**Comment by jimni1222** [comment]
This issue is fixed with https://github.com/klaytn/caver-js/pull/82
Can you rebase your branch on latest dev?
